// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rozliczeniaPIT.Models;

#nullable disable

namespace pitWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413114826_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("rozliczeniaPIT.Models.RozliczenieModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PodatekNalezy")
                        .HasColumnType("TEXT");

                    b.Property<int>("RokPodatkowy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rozliczenia");
                });
#pragma warning restore 612, 618
        }
    }
}
